depth_settings:
  depth_test_enabled: true
  depth_compare_op: LESS
rasterization_settings:
  polygon_mode: FILL
  cull_mode: BACK
  front_face: COUNTER_CLOCKWISE
  line_width: 1.0
image_settings:
  filter_mode: NEAREST
  address_mode: REPEAT
  anisotropy_enabled: false
  anisotropy_amount: 16
  mip_map_mode: NEAREST
debug_settings:
  collision_debug_enabled: true
  debug_line_width: 5.0
